version: '3.1'
## ejecutar
## docker compose up -d
services:
  admin:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # hacer contraseña vacía

  billing:
    image: mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # hacer contraseña vacía

  maintenance:
    image: mysql
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # hacer contraseña vacía

  monopatin:
    image: mysql
    ports:
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # hacer contraseña vacía

  phpmyadminmonopatin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"                 # phpMyAdmin disponible en localhost:8081
    environment:
      PMA_HOST: monopatin                # Nombre del servicio MySQL (monopatin)
      #MYSQL_ROOT_PASSWORD:   # La contraseña root para acceder a MySQL desde phpMyAdmin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  reports:
    image: mysql
    ports:
      - "3310:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # hacer contraseña vacía

  user:
    image: mysql
    ports:
      - "3311:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # hacer contraseña vacía

  phpmyadminuser:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"                 # phpMyAdmin disponible en localhost:8080
    environment:
      PMA_HOST: user                # Nombre del servicio MySQL (user)
      #MYSQL_ROOT_PASSWORD:   # La contraseña root para acceder a MySQL desde phpMyAdmin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

## docker run -d --name mysqlUsuarios -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 mysql