openapi: 3.0.0

info: 
  version: 1.0.0
  title: TPE Arquitecturas Web TUDAI - GRUPO 1
  description: API de Aplicación para Monopatines Eléctricos
servers:
- url: http://localhost:8080
tags:
- name: usuarios
  description: Maneja los usuarios y tokens
- name: admin
  description: Solo los usuarios con rol admin acceden
- name: facturacion
  description: Maneja la información acerca de las facturaciones
- name: monopatines
  description: Maneja la información acerca de los monopatines
- name: mantenimiento
  description: Maneja la información acerca de los monopatines en mantenimiento y solo se puede acceder siendo de encargado de mantenimiento
  
paths:
  /api/users:
    post:
      tags:
      - usuarios
      summary: Crea un usuario
      description: Crea un usuario sin necesidad de token y devuelve el usuario cargado
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreacionUsuario"
      responses:
        201:
          description: El usuario fue cargado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
                
  /api/authenticate:
    post:
      summary: Devuelve un token
      tags:
      - usuarios
      requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidarUsuario"
      responses:
        200:
          description: (CREATED) El usuario fue cargado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
                
  /admin/role/{role}:
    get:
      tags:
      - admin
      - usuarios
      summary: Devuelve los usuarios con determinado rol
      parameters:
      - $ref: "#/components/parameters/token"
      - name: role
        in: path
        description: filtro de rol
        required: true
        schema:
          type: string
      responses:
        200:
          description: devolvió una lista de los usuarios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaUsuarios'
                
  /admin/null/{id_acc}:
    put:
      tags:
      - admin
      - usuarios
      summary: Anula la cuenta de un usuario
      parameters:
      - $ref: "#/components/parameters/token"
      - name: id_acc
        in: path
        description: id de la cuenta a anular
        required: true
        schema:
          type: number
      responses:
        201:
          description: se anuló la cuenta indicada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
                
  /admin/xViajes/{xViajes}/anio/{anio}:
    get:
      tags:
      - admin
      - monopatines
      summary: Obtiene monopatines por x viajes por año
      parameters:
      - $ref: "#/components/parameters/token"
      - name: xViajes
        in: path
        description: filtro de cantidad de viajes
        required: true
        schema:
          type: number
      - name: anio
        in: path
        description: filtro de año
        required: true
        schema:
          type: number
      responses:
        200:
          description: devolvió una lista de los monopatines con los filtros indicados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaMonopatines'
                
  /admin/totalBilled/origen/{fechaOrigen}/fin/{fechaFin}:
    get:
      tags:
      - admin
      - facturacion
      summary: Obtiene el total facturado entre dos fechas
      parameters:
      - $ref: "#/components/parameters/token"
      - name: fechaOrigen
        in: path
        description: fecha inicio
        required: true
        schema:
          type: string
      - name: fechaFin
        in: path
        description: fecha fin
        required: true
        schema:
          type: string
      responses:
        200:
          description: devolvió el reporte con los datos necesarios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReporteFacturacion'
  
  /admin/activosVsMantenimiento:
    get:
      tags:
      - admin
      - monopatines
      summary: Provee una comparacion de la cantidad de monopatines activos versus la cantidad en mantenimiento
      parameters:
      - $ref: "#/components/parameters/token"
      responses:
        200:
          description: devolvió el reporte con la comparación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReporteMonopatinesEstado'
                
  /admin/newBilling:
    post:
      summary: Setea un nuevo precio fijo y/o extra
      tags:
      - admin
      - facturacion
      parameters:
      - $ref: "#/components/parameters/token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Facturacion"
      responses:
        201:
          description: devolvió la nueva facturacion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntidadFacturacion'
      
  /bills:
    get:
      summary: Obtiene todas las facturaciones
      tags:
      - facturacion
      parameters:
      - $ref: "#/components/parameters/token"
      responses:
        200:
          description: devolvió una lista con las facturaciones
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaFacturacion'

  /monopatin:
    get:
      summary: Obtiene todos los monopatines
      tags:
        - monopatines
      parameters:
        - $ref: "#/components/parameters/token"
      responses:
        200:
          description: se devolvió la lista de monopatines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaMonopatines'
    post:
      summary: Agrega un monopatín
      tags:
        - monopatines
        - admin
      parameters:
        - $ref: "#/components/parameters/token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreacionMonopatin'
      responses:
        201:
          description: se devolvió el monopatín creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monopatin'

  /monopatin/id/{id_monopatin}:
    get:
      summary: Obtiene un monopatín
      tags:
        - monopatines
      parameters:
        - $ref: "#/components/parameters/token"
        - name: id_monopatin
          in: path
          description: id del monopatín a obtener
          required: true
          schema:
            type: number
      responses:
        200:
          description: se devolvió el monopatín con la id especificada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monopatin'

  /monopatin/{id_monopatin}:
    get:
      summary: Borra un monopatín
      tags:
        - monopatines
        - admin
      parameters:
        - $ref: "#/components/parameters/token"
        - name: id_monopatin
          in: path
          description: id del monopatín a borrar
          required: true
          schema:
            type: number
      responses:
        200:
          description: se devolvió el monopatín eliminado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Monopatin'

  /monopatin/location/{posx}/{posy}:
    get:
      summary: Obtiene los monopatines más cercanos a una posición
      tags:
        - monopatines
      parameters:
        - $ref: "#/components/parameters/token"
        - name: posx
          in: path
          description: posición x del usuario
          required: true
          schema:
            type: number
        - name: posy
          in: path
          description: posición y del usuario
          required: true
          schema:
            type: number
      responses:
        200:
          description: se devolvió la lista de monopatines cercanos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaMonopatines'

  
  /mantenimiento:
    get:
      summary: Obtiene una lista de todos los mantenimientos
      tags:
      - mantenimiento
      parameters:
      - $ref: "#/components/parameters/token"
      responses:
        200:
          description: se devolvió la lista correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaMantenimientos'
  
  /mantenimiento/estado/{status}:
    get:
      summary: Obtiene mantenimientos por estados
      tags:
      - mantenimiento
      parameters:
      - $ref: "#/components/parameters/token"
      - name: status
        in: path
        description: filtro de estado
        required: true
        schema:
          type: string
      responses:
        200:
          description: se devolvió la lista de mantenimientos filtrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaMantenimientos'
      
  /mantenimiento/{id_monopatin}:
    post:
      summary: Agrega un monopatín a mantenimiento
      tags:
      - mantenimiento
      parameters:
      - $ref: "#/components/parameters/token"
      - name: id_monopatin
        in: path
        description: id del monopatín a agregar a mantenimiento
        required: true
        schema:
          type: number
      responses:
        201:
          description: se devolvió el mantenimiento recién agregado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mantenimiento'
    get:
      summary: Obtiene un mantenimiento por el id del monopatín
      tags:
      - mantenimiento
      parameters:
      - $ref: "#/components/parameters/token"
      - name: id_monopatin
        in: path
        description: id del monopatín
        required: true
        schema:
          type: number
      responses:
        200:
          description: se devolvió el mantenimiento encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mantenimiento'
      
  /id/{id_monopatin}/estado/{status}:
    put:
      summary: Modifica el estado de un monopatín
      tags:
      - mantenimiento
      parameters:
      - $ref: "#/components/parameters/token"
      - name: id_monopatin
        in: path
        description: id del monopatín a modificar
        required: true
        schema:
          type: number
      - name: status
        in: path
        description: nuevo estado del monopatín
        required: true
        schema:
          type: string
      responses:
        200:
          description: se devolvió el mantenimiento recién modificado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mantenimiento'

  /monopatinesKm/pausa/{pausa}:
    get:
      summary: obtener un reporte de monopatines ordenado por kilometros, con o sin tiempos de pausa
      tags:
        - mantenimiento
      parameters:
        - $ref: "#/components/parameters/token"
        - name: pausa
          in: path
          description: boolean que indica si se incluyen o no los tiempos de pausa
          type: boolean
          required: true
      responses:
        200:
          description: se devolvió un listado de reportes
          content:
            application/json:
              schema:
                type: array
        500:
          description: internal server error
          content:
            application/json:
              schema:
                type: string

      
      
components:
  parameters:
    token:
      name: token
      in: header
      description: Token de autorización para acceder a los recursos
      required: true
      schema:
        type: string
  
  schemas:
    token:
      type: object
      description: token JWT para autenticar las llamadas a endpoints
      properties:
        token_id:
          type: string
          description: token JWT
          
    ListaUsuarios:
      type: array
      items:
        $ref: "#/components/schemas/Usuario"
  
    ListaMonopatines:
      type: array
      items:
        $ref: "#/components/schemas/Monopatin"
        
    CreacionUsuario:
      type: object
      properties:
        nombre:
          type: string
          description: nombre del usuario
        apellido:
          type: string
          description: apellido del usuario
        numeroCelular:
          type: number
          description: celular del usuario
        email:
          type: string
          description: email del usuario
        password:
          type: string
          description: contraseña del usuario
        id_rol:
          type: number
          description: id del rol a asignar
          
    Usuario:
      type: object
      properties:
        id:
          type: number
          description: id del usuario
        nombre:
          type: string
          description: nombre del usuario
        apellido:
          type: string
          description: apellido del usuario
        numeroCelular:
          type: number
          description: celular del usuario
        email:
          type: string
          description: email del usuario
        password:
          type: string
          description: contraseña del usuario
        role:
          $ref: '#/components/schemas/RolUsuario'
        
    RolUsuario:
      type: object
      properties:
        id:
          type: number
          description: id del rol
        role:
          type: string
          description: tipo de rol
          
    Cuenta:
      type: object
      properties:
        id:
          type: number
          description: id de la cuenta
        creatin_date:
          type: string
          description: fecha de creacion de la cuenta
        balance:
          type: number
          description: balance de la cuenta
        anullated:
          type: boolean
          description: marca si la cuenta está anulada o no
    
    Viaje:
        properties:
          id:
            type: number
            description: id del viaje
          duracion:
            type: number
            description: duracion del viaje
          fecha:
            type: string
            description: fecha del viaje
          id_usuario:
            type: number
            description: id del usuario
          monopatin:
            $ref: '#/components/schemas/Monopatin'

    CreacionMonopatin:
      type: object
      properties:
        kmRecorridos:
          type: number
          description: los km que recorrió el monopatin
        id_parada:
          type: number
          description: id de la parada actual o null

    Monopatin:
      type: object
      properties:
        id:
          type: number
          description: id del monopatin
        kmRecorridos:
          type: number
          description: los km que recorrió el monopatin
        parada:
          $ref: '#/components/schemas/Parada'

    Parada:
      type: object
      properties:
        id:
          type: number
          description: id de la parada
        isHabilitada:
          type: boolean
          description: true si está libre false si está ocupada
          
    ReporteFacturacion:
      type: object
      properties:
        nombre:
          type: string
          description: nombre del reporte
        descripcion:
          type: string
          description: descripcion del reporte
        totalFacturado:
          type: number
          description: valor final de la facturacion
        fechaInicio:
          type: string
          description: fecha de inicio del reporte
        fechaFin:
          type: string
          description: fecha de fin del reporte
          
    ReporteMonopatinesEstado:
      type: object
      properties:
        nombre:
          type: string
          description: nombre del reporte
        descripcion:
          type: string
          description: descripcion del reporte
        cantActivos:
          type: number
          description: cantidad de monopatines activos
        cantMantenimiento:
          type: number
          description: cantidad de monopatines en mantenimiento
          
    Facturacion:
      type: object
      properties:
        fechaInicioFacturacionNueva:
          type: string
          description: a partir de que fecha serán validos los nuevos precios
        precioFijo:
          type: number
          description: precio de tarifa fijo
        precioExtra:
          type: number
          description: precio de tarifa extra
          
    EntidadFacturacion:
      type: object
      properties:
        id:
          type: number
          description: id de la facturacion
        fecha:
          type: string
          description: fecha de vigencia de la facturacion
        price:
          type: number
          description: precio de tarifa fijo
        additionalPrice:
          type: number
          description: precio de tarifa extra
    
    ValidarUsuario: 
      type: object
      properties:
        email:
          type: string
          description: email del usuario
        password:
          type: string
          description: contraseña del usuario
    
    ListaFacturacion:
      type: array
      items:
        $ref: "#/components/schemas/EntidadFacturacion"
        
    ListaMantenimientos:
      type: array
      items:
        $ref: '#/components/schemas/Mantenimiento'
        
    Mantenimiento:
      type: object
      properties:
        id:
          type: number
          description: id del mantenimiento
        id_monopatin:
          type: number
          description: id del monopatin en mantenimiento
        estado:
          type: string
          description: estado del monopatin en mantenimiento
          
          
          
          
          
          
          
          
          
          
      