spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user
            uri: http://localhost:8011
            predicates:
              - Path=/users/**
        default-filters:
          - RemoveRequestHeader=Cookie
logging:
  level:
    org.springframework.cloud.gateway: DEBUG